Documentation/Addition of Required Documentation
gopavasanth/WhatsApp-Karo pull request #7
Opened 2023-10-03 21:07 UTC by ayato91

Here the required documents for the Hacktoberfest. Give a label to your repository as Hacktober and we are all set :)
for #3

2023-10-09 14:26 UTC, immadisairaj requested changes

2023-10-09 14:26 UTC, immadisairaj commented on CONTRIBUTING.md
> +- Styling/code can be pretty, ugly or stupid, big or small as long as it works
Sorry, but code has to follow some standards. Formatting and style of writing code has to be good. "as long as it works" is not acceptable. Can you please update.

2023-10-09 14:26 UTC, immadisairaj commented on CONTRIBUTING.md
> +- You are allowed to make pull requests. We just merge it ;)
We don't just merge it. We review and then merge. So, you can remove that sentence and just keep Anyone is allowed to make a PR.

2023-10-09 14:26 UTC, immadisairaj commented on CONTRIBUTING.md
> +- Try to keep pull requests small to minimize merge conflicts
A PR can be big. It just needs to fit in one feature. So, I think rephrasing is needed.

2023-10-09 14:26 UTC, immadisairaj commented on CONTRIBUTING.md
> +
I think we need to include that to work on projects, Flutter is needed. (Not exactly at this place but somewhere).

2023-10-09 14:26 UTC, immadisairaj commented on CONTRIBUTING.md
> +```markdown
For all commands related, you can keep sh instead of markdown

2023-10-09 16:28 UTC, ayato91 commented
@immadisairaj Thanks for your valuable reviews. All requested changes are on the way :)

2023-10-20 07:15 UTC, immadisairaj reviewed
Looks Good, I have made a few changes, once that are done, it's ready to be merged. Thank you for your contribution. And, sorry for delay in the review. I am currently on vacation..

2023-10-20 07:15 UTC, immadisairaj commented on CODE_OF_CONDUCT.md
> +contact@openfoodfacts.org.
```suggestion
gopavasanth1999@gmail.com
```

Contact is different :)

2023-10-20 07:15 UTC, immadisairaj commented on CONTRIBUTING.md
> +- Do NOT remove other content.
```suggestion
- Do NOT remove other content unless necessary.
```

2023-10-20 07:15 UTC, immadisairaj commented on CONTRIBUTING.md
> +- Styling/code should follow some standards.
```suggestion
- Styling/code should follow community standards (eg. proper code formatting).
```

2023-10-20 07:15 UTC, immadisairaj commented on CONTRIBUTING.md
> +- PRs can be Big or Small. It will be reviewed and then only it will be merged/accepted.
```suggestion
- PR's can be Big or Small. Don't be afraid to open a PR, you will always get help.
```

2023-10-20 07:15 UTC, immadisairaj commented on CONTRIBUTING.md
> +This app is written in Flutter. Even though Flutter is cross-platform, This app is currently focused on Android or iOS. So in order to setup and run the project locally, you need to have an emulator(
```suggestion
This app is written in Flutter. Even though Flutter is cross-platform, This app is currently focused on Android or iOS. So in order to setup and run the project locally, you need to have an emulator(android or iOS) or a real device. And more importantly, flutter installed.
```

It's just a suggestion, feel free to keep it how it looks good.

2023-10-20 07:18 UTC, merged

2023-10-20 12:20 UTC, immadisairaj commented
@gopavasanth there are some changes requested. I just put the `hacktoberfest-accepted` label so that it's almost done and accepted for the hacktoberfest but not merge.

@ayato91 can you please make the changes and send a new PR for it? Because some information like contact are not proper.